apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: alim
  labels:
    app: web-alim
  name: web-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-alim
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-alim
    spec:
      containers:
        - image: depo.jandarma.gov.tr/alim/web-test:#{Build.SourceVersion}#-#{Build.BuildId}#
          imagePullPolicy: IfNotPresent
          name: web-test
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 1500m
              memory: 4000Mi
            requests:
              cpu: 50m
              memory: 250Mi
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 40
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          # envFrom:
          #   - configMapRef:
          #       name: web-test-config
          # volumeMounts:
          #   - name: env
          #     mountPath: /usr/share/nginx/html/.env
          #     subPath: .env
          securityContext:
            runAsUser: 0
      # volumes:
      #   - name: env
      #     configMap:
      #       name: web-test-config
      #       items:
      #         - key: .env
      #           path: .env
      imagePullSecrets:
        - name: alim-image-pull-secret
