// <auto-generated />
using System;
using AdminBackend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminBackend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JugaAIDbContext))]
    [Migration("20251006154527_update-application-types")]
    partial class updateapplicationtypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jugaai")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminBackend.Domain.Entities.Application", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("CheckHallucination")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EnableGuardRails")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasApplicationFile")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUserFile")
                        .HasColumnType("boolean");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("MemoryTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("OutputTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationTypeId");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("MemoryTypeId");

                    b.HasIndex("OutputTypeId");

                    b.ToTable("Applications", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationTypeId = 1L,
                            CheckHallucination = true,
                            Description = "This is a test application for the AI Orchestrator.",
                            EnableGuardRails = true,
                            HasApplicationFile = true,
                            HasUserFile = false,
                            Identifier = "test-app",
                            MemoryTypeId = 2L,
                            Name = "Test App",
                            OutputTypeId = 3L,
                            SystemPrompt = "You are a helpful AI assistant."
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationChunkingStrategy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ChunkSize")
                        .HasColumnType("integer");

                    b.Property<long>("ChunkingStrategyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Overlap")
                        .HasColumnType("integer");

                    b.Property<string>("Seperator")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("ChunkingStrategyId");

                    b.ToTable("ApplicationChunkingStrategies", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1L,
                            ChunkSize = 2000,
                            ChunkingStrategyId = 3L,
                            Overlap = 200
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationEmbedding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("EmbeddingId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("EmbeddingId");

                    b.HasIndex("ApplicationId", "EmbeddingId")
                        .IsUnique();

                    b.ToTable("ApplicationEmbeddings", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1L,
                            EmbeddingId = 3L
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationExtractorEngine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ExtractorEngineTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("ExtractorEngineTypeId");

                    b.ToTable("ApplicationExtractorEngines", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1L,
                            ExtractorEngineTypeId = 1L
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationFileStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FileStoreId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("FileStoreId");

                    b.HasIndex("ApplicationId", "FileStoreId")
                        .IsUnique();

                    b.ToTable("ApplicationFileStores", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1L,
                            FileStoreId = 1L
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationLlm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EnableThinking")
                        .HasColumnType("boolean");

                    b.Property<long>("LlmId")
                        .HasColumnType("bigint");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<float>("TopP")
                        .HasColumnType("real");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("LlmId");

                    b.HasIndex("ApplicationId", "LlmId")
                        .IsUnique();

                    b.ToTable("ApplicationLlms", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1L,
                            EnableThinking = false,
                            LlmId = 6L,
                            Temperature = 0f,
                            TopP = 0.7f
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationMcpServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("McpServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("McpServerId");

                    b.HasIndex("ApplicationId", "McpServerId")
                        .IsUnique();

                    b.ToTable("ApplicationMcpServers", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1L,
                            McpServerId = 1L
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationSearchEngine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("EmbeddingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SearchEngineId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VectorSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("EmbeddingId");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("SearchEngineId");

                    b.ToTable("ApplicationSearchEngines", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1L,
                            EmbeddingId = 3L,
                            Identifier = "test-app-local-index",
                            IndexName = "test-app-index",
                            SearchEngineId = 1L,
                            VectorSize = 2560
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("ApplicationTypes", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "REACT"
                        },
                        new
                        {
                            Id = 2L,
                            Identifier = "CHATBOT"
                        },
                        new
                        {
                            Id = 3L,
                            Identifier = "AGENTIC_RAG"
                        },
                        new
                        {
                            Id = 4L,
                            Identifier = "REFLECTIVE_RAG"
                        },
                        new
                        {
                            Id = 5L,
                            Identifier = "MCP_POWERED_AGENTIC_RAG"
                        },
                        new
                        {
                            Id = 99L,
                            Identifier = "CUSTOM"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ChunkingStrategy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsChunkingSizeRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOverlapRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("ChunkingStrategies", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "fixed-size",
                            IsChunkingSizeRequired = true,
                            IsOverlapRequired = true
                        },
                        new
                        {
                            Id = 2L,
                            Identifier = "html",
                            IsChunkingSizeRequired = true,
                            IsOverlapRequired = true
                        },
                        new
                        {
                            Id = 3L,
                            Identifier = "markdown",
                            IsChunkingSizeRequired = true,
                            IsOverlapRequired = true
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.Embedding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("LlmProviderId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxInputTokenSize")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("VectorSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LlmProviderId");

                    b.ToTable("Embeddings", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32768,
                            ModelName = "lm_studio/text-embedding-qwen3-embedding-4b",
                            Url = "http://127.0.0.1:4000",
                            VectorSize = 2560
                        },
                        new
                        {
                            Id = 2L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32768,
                            ModelName = "ollama/dengcao/Qwen3-Embedding-8B:Q8_0",
                            Url = "http://127.0.0.1:4000",
                            VectorSize = 2560
                        },
                        new
                        {
                            Id = 3L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32768,
                            ModelName = "remote-ollama/dengcao/Qwen3-Embedding-4B:Q8_0",
                            Url = "http://127.0.0.1:4000",
                            VectorSize = 2560
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ExtractorEngineType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Pdf")
                        .HasColumnType("boolean");

                    b.Property<bool>("Txt")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Word")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("ExtractorEngineTypes", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "markitdown",
                            Pdf = true,
                            Txt = true,
                            Word = true
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileStoreId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileStoreIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngestionStatusTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("UploadApplicationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FileStoreId");

                    b.HasIndex("FileTypeId");

                    b.HasIndex("IngestionStatusTypeId");

                    b.ToTable("Files", "jugaai");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.FileStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("FileStores", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "s3",
                            Uri = "127.0.0.1:8090"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.FileType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("FileTypes", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Identifier = "Personal"
                        },
                        new
                        {
                            Id = 2,
                            Identifier = "Application"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.IngestionStatusType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("IngestionStatusTypes", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Identifier = "ProcessingRequested"
                        },
                        new
                        {
                            Id = 2,
                            Identifier = "Extracting"
                        },
                        new
                        {
                            Id = 3,
                            Identifier = "Chunking"
                        },
                        new
                        {
                            Id = 4,
                            Identifier = "Indexing"
                        },
                        new
                        {
                            Id = 5,
                            Identifier = "Processed"
                        },
                        new
                        {
                            Id = 6,
                            Identifier = "DeletingRequested"
                        },
                        new
                        {
                            Id = 7,
                            Identifier = "ProcessingFailed"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.Llm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("LlmProviderId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxInputTokenSize")
                        .HasColumnType("integer");

                    b.Property<int>("MaxOutputTokenSize")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("LlmProviderId");

                    b.ToTable("Llms", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32768,
                            MaxOutputTokenSize = 16000,
                            ModelName = "ollama/qwen3:14b",
                            Url = "http://127.0.0.1:4000"
                        },
                        new
                        {
                            Id = 2L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32000,
                            MaxOutputTokenSize = 16000,
                            ModelName = "ollama/qwen3:30b",
                            Url = "http://127.0.0.1:4000"
                        },
                        new
                        {
                            Id = 3L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32000,
                            MaxOutputTokenSize = 16000,
                            ModelName = "ollama/qwen3:32b",
                            Url = "http://127.0.0.1:4000"
                        },
                        new
                        {
                            Id = 4L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32000,
                            MaxOutputTokenSize = 16000,
                            ModelName = "ollama/deepseek-r1:32b",
                            Url = "http://127.0.0.1:4000"
                        },
                        new
                        {
                            Id = 5L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32000,
                            MaxOutputTokenSize = 16000,
                            ModelName = "remote-ollama/qwen3:14b",
                            Url = "http://127.0.0.1:4000"
                        },
                        new
                        {
                            Id = 6L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32000,
                            MaxOutputTokenSize = 16000,
                            ModelName = "remote-ollama/qwen3:32b",
                            Url = "http://127.0.0.1:4000"
                        },
                        new
                        {
                            Id = 7L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32000,
                            MaxOutputTokenSize = 16000,
                            ModelName = "remote-ollama/gpt-oss:20b",
                            Url = "http://127.0.0.1:4000"
                        },
                        new
                        {
                            Id = 8L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32000,
                            MaxOutputTokenSize = 16000,
                            ModelName = "ollama/gpt-oss:20b",
                            Url = "http://127.0.0.1:4000"
                        },
                        new
                        {
                            Id = 9L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32000,
                            MaxOutputTokenSize = 16000,
                            ModelName = "hosted_vllm/Qwen/Qwen3-14B",
                            Url = "http://127.0.0.1:4000"
                        },
                        new
                        {
                            Id = 10L,
                            LlmProviderId = 1L,
                            MaxInputTokenSize = 32000,
                            MaxOutputTokenSize = 16000,
                            ModelName = "hosted_vllm/Qwen/Qwen3-14B-AWQ",
                            Url = "http://127.0.0.1:4000"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.LlmProvider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProviders", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "LiteLlm"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.McpServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("McpServers", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "toolgateway",
                            Uri = "http://localhost:5164/api/mcp"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.MemoryType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("MemoryTypes", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "MEMORY"
                        },
                        new
                        {
                            Id = 2L,
                            Identifier = "MONGO"
                        },
                        new
                        {
                            Id = 3L,
                            Identifier = "POSTGRE"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.OutputType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("OutputTypes", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "BLOCK"
                        },
                        new
                        {
                            Id = 2L,
                            Identifier = "STREAMING"
                        },
                        new
                        {
                            Id = 3L,
                            Identifier = "BOTH"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.SearchEngine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("SearchEngineTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("SearchEngineTypeId");

                    b.ToTable("SearchEngines", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "elastic-local",
                            SearchEngineTypeId = 1L,
                            Url = "http://127.0.0.1:9200"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.SearchEngineType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("SearchEngineTypes", "jugaai");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "elasticsearch"
                        });
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.Application", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.ApplicationType", "ApplicationType")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.MemoryType", "MemoryType")
                        .WithMany("Applications")
                        .HasForeignKey("MemoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.OutputType", "OutputType")
                        .WithMany("Applications")
                        .HasForeignKey("OutputTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationType");

                    b.Navigation("MemoryType");

                    b.Navigation("OutputType");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationChunkingStrategy", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.Application", "Application")
                        .WithOne("ApplicationChunkingStrategy")
                        .HasForeignKey("AdminBackend.Domain.Entities.ApplicationChunkingStrategy", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.ChunkingStrategy", "ChunkingStrategy")
                        .WithMany("ApplicationChunkingStrategies")
                        .HasForeignKey("ChunkingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ChunkingStrategy");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationEmbedding", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.Application", "Application")
                        .WithOne("ApplicationEmbedding")
                        .HasForeignKey("AdminBackend.Domain.Entities.ApplicationEmbedding", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.Embedding", "Embedding")
                        .WithMany()
                        .HasForeignKey("EmbeddingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Embedding");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationExtractorEngine", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.Application", "Application")
                        .WithOne("ApplicationExtractorEngine")
                        .HasForeignKey("AdminBackend.Domain.Entities.ApplicationExtractorEngine", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.ExtractorEngineType", "ExtractorEngineType")
                        .WithMany("ApplicationExtractorEngines")
                        .HasForeignKey("ExtractorEngineTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ExtractorEngineType");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationFileStore", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.Application", "Application")
                        .WithOne("ApplicationFileStore")
                        .HasForeignKey("AdminBackend.Domain.Entities.ApplicationFileStore", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.FileStore", "FileStore")
                        .WithMany("ApplicationFileStores")
                        .HasForeignKey("FileStoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("FileStore");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationLlm", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.Application", "Application")
                        .WithOne("ApplicationLlm")
                        .HasForeignKey("AdminBackend.Domain.Entities.ApplicationLlm", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.Llm", "Llm")
                        .WithMany()
                        .HasForeignKey("LlmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Llm");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationMcpServer", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.Application", "Application")
                        .WithMany("ApplicationMcpServers")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.McpServer", "McpServer")
                        .WithMany("ApplicationMcpServers")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationSearchEngine", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.Application", "Application")
                        .WithOne("ApplicationSearchEngine")
                        .HasForeignKey("AdminBackend.Domain.Entities.ApplicationSearchEngine", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.Embedding", "Embedding")
                        .WithMany("ApplicationSearchEngines")
                        .HasForeignKey("EmbeddingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.SearchEngine", "SearchEngine")
                        .WithMany("ApplicationSearchEngines")
                        .HasForeignKey("SearchEngineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Embedding");

                    b.Navigation("SearchEngine");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.Embedding", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.LlmProvider", "LlmProvider")
                        .WithMany("Embeddings")
                        .HasForeignKey("LlmProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LlmProvider");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.File", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.FileStore", "FileStore")
                        .WithMany("Files")
                        .HasForeignKey("FileStoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.FileType", "FileType")
                        .WithMany("Files")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminBackend.Domain.Entities.IngestionStatusType", "IngestionStatusType")
                        .WithMany("Files")
                        .HasForeignKey("IngestionStatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileStore");

                    b.Navigation("FileType");

                    b.Navigation("IngestionStatusType");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.Llm", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.LlmProvider", "LlmProvider")
                        .WithMany("Llms")
                        .HasForeignKey("LlmProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LlmProvider");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.SearchEngine", b =>
                {
                    b.HasOne("AdminBackend.Domain.Entities.SearchEngineType", "SearchEngineType")
                        .WithMany("SearchEngines")
                        .HasForeignKey("SearchEngineTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SearchEngineType");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.Application", b =>
                {
                    b.Navigation("ApplicationChunkingStrategy")
                        .IsRequired();

                    b.Navigation("ApplicationEmbedding")
                        .IsRequired();

                    b.Navigation("ApplicationExtractorEngine")
                        .IsRequired();

                    b.Navigation("ApplicationFileStore")
                        .IsRequired();

                    b.Navigation("ApplicationLlm")
                        .IsRequired();

                    b.Navigation("ApplicationMcpServers");

                    b.Navigation("ApplicationSearchEngine")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ApplicationType", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ChunkingStrategy", b =>
                {
                    b.Navigation("ApplicationChunkingStrategies");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.Embedding", b =>
                {
                    b.Navigation("ApplicationSearchEngines");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.ExtractorEngineType", b =>
                {
                    b.Navigation("ApplicationExtractorEngines");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.FileStore", b =>
                {
                    b.Navigation("ApplicationFileStores");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.FileType", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.IngestionStatusType", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.LlmProvider", b =>
                {
                    b.Navigation("Embeddings");

                    b.Navigation("Llms");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.McpServer", b =>
                {
                    b.Navigation("ApplicationMcpServers");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.MemoryType", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.OutputType", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.SearchEngine", b =>
                {
                    b.Navigation("ApplicationSearchEngines");
                });

            modelBuilder.Entity("AdminBackend.Domain.Entities.SearchEngineType", b =>
                {
                    b.Navigation("SearchEngines");
                });
#pragma warning restore 612, 618
        }
    }
}
